apiVersion: v1
kind: Secret
metadata:
  name: vcluster-platform
  namespace: pre-prod-gate
  labels:
    kargo.akuity.io/cred-type: generic
type: Opaque
stringData:
  token: <replace-with-platform-api-token>
