apiVersion: v1
kind: Service
metadata:
  name: vcluster-wakeup-proxy
  namespace: argocd
  labels:
    app.kubernetes.io/name: vcluster-wakeup-proxy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vcluster-wakeup-proxy
  ports:
    - name: http
      port: 8080
      targetPort: http
