name: build-and-push-ghcr

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional extra image tag (e.g., 0.1.2)"
        required: false
        default: ""
  release:
    types: [ published, edited ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: vcluster-wakeup-proxy
  REGISTRY: ghcr.io
  PLATFORMS: linux/amd64,linux/arm64

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            # latest on main
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # git SHA
            type=sha
            # branch name (e.g., main)
            type=ref,event=branch
            # manual input tag for workflow_dispatch
            type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag != '' }}
            # semver tags on releases (e.g., v1.2.3 -> 1.2.3, 1.2, 1)
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
          # If your tags are like "v1.2.3", metadata-action strips the "v" automatically for semver

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
